// How to create api gateway :- create new service for api gateway and import APIGATEWAY package.
// application.propertise file :- we have to create application routing
// you have to add eureca server and gateway cloud dependecies

server:
  port: 8083
  
spring:
  application:
    name: API_GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICE
        uri:
         lb://CITIZEN-SERVICE
        predicates:
        - Path=/citizen/**
      
      - id: VACCINATION-CENTER-SERVICE
        uri:
         lb://VACCINATION-CENTER-SERVICE
        predicates:
        - Path=/vaccinationcenter/**
          
        
